[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/library"
  to = "/library.html"
  status = 200

[[redirects]]
  from = "/manufacturers"
  to = "/manufacturers.html"
  status = 200

[[redirects]]
  from = "/specsheets"
  to = "/specsheets.html"
  status = 200

[[redirects]]
  from = "/insights"
  to = "/insights.html"
  status = 200

[[redirects]]
  from = "/subscribe"
  to = "/subscribe.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200
